image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

default:
  before_script:
    - mv $FIREBASE_CRED src/app/firebase-config.ts

deploy_dev:
  variables:
    SERVICE_NAME: beta.codex.brussels
  script:
    - npm install
    - npm run deploy
  only:
    - develop
  tags:
    - bash

deploy_prd:
  variables:
    SERVICE_NAME: codex.brussels
  script:
    - npm install
    - npm run deploy:prd
  only:
    - master
  tags:
    - bash
