resources:
  - name: codex-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/Tyranwyn/codex-bruxellensis-pwa
      branch: master

jobs:
  - name: build
    plan:
      - get: codex-git
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: node, tag: "10" }
          inputs:
            - name: codex-git
          params:
            NG_CLI_ANALYTICS: ci
          run:
            path: /bin/sh
            args:
              - -c
              - |
                echo "Node Version: $(node --version)"
                echo "NPM Version: $(npm --version)"
                cd codex-git
                echo "((firebase-config))" > src/app/firebase-config.ts
                npm install
                npm run build
